version: '3.8'

services:
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DB_URI=mongodb://mongo:27017/catoffdb  # Connect to the MongoDB service
      - JWT_SECRET=${JWT_SECRET}  # Secrets can be passed from your environment or defined here
    depends_on:
      - mongo  # Ensures MongoDB starts before the API
    volumes:
      - .:/usr/src/app  # Mounts the project directory for live updates in development
    command: npm start  # Adjust if needed (e.g., `node server.js`)

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db  # Persists MongoDB data

volumes:
  mongo_data:  # Named volume to persist MongoDB data
